config/routes.rb
Rails.application.routes.draw do

  resources :likes
  resources :idiomas
  resources :noticia
  resources :agrupadores
  resources :estatuses
  resources :categoria

 namespace :api do
  namespace :v1 do 
    resources :noticia, path: "/news"
    resources :app
    resources :like , path: "/like"
  end
 end

    get 'noticia' => 'noticia#index', as: :noticia_index
    get 'categoria' => 'categoria#index', as: :categoria_index

end

app/models/agrupadore.rb
class Agrupadore < ActiveRecord::Base
end

app/controllers/agrupadores_controller.rb
class AgrupadoresController < ApplicationController
  before_action :set_agrupadore, only: [:show, :edit, :update, :destroy]

  # GET /agrupadores
  # GET /agrupadores.json
  def index
    @agrupadores = Agrupadore.all
  end

  # GET /agrupadores/1
  # GET /agrupadores/1.json
  def show
  end

  # GET /agrupadores/new
  def new
    @agrupadore = Agrupadore.new
  end

  # GET /agrupadores/1/edit
  def edit
  end

  # POST /agrupadores
  # POST /agrupadores.json
  def create
    @agrupadore = Agrupadore.new(agrupadore_params)

    respond_to do |format|
      if @agrupadore.save
        format.html { redirect_to @agrupadore, notice: 'Agrupadore was successfully created.' }
        format.json { render :show, status: :created, location: @agrupadore }
      else
        format.html { render :new }
        format.json { render json: @agrupadore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agrupadores/1
  # PATCH/PUT /agrupadores/1.json
  def update
    respond_to do |format|
      if @agrupadore.update(agrupadore_params)
        format.html { redirect_to @agrupadore, notice: 'Agrupadore was successfully updated.' }
        format.json { render :show, status: :ok, location: @agrupadore }
      else
        format.html { render :edit }
        format.json { render json: @agrupadore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agrupadores/1
  # DELETE /agrupadores/1.json
  def destroy
    @agrupadore.destroy
    respond_to do |format|
      format.html { redirect_to agrupadores_url, notice: 'Agrupadore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agrupadore
      @agrupadore = Agrupadore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agrupadore_params
      params.require(:agrupadore).permit(:titulo, :idioma_id)
    end
end

app/helpers/agrupadores_helper.rb
module AgrupadoresHelper
end

app/views/agrupadores/_form.html.erb
<%= form_for(@agrupadore) do |f| %>
  <% if @agrupadore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agrupadore.errors.count, "error") %> prohibited this agrupadore from being saved:</h2>

      <ul>
      <% @agrupadore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :idioma_id %><br>
    <%= f.collection_select :idioma_id, Idioma.order(:titulo), :id, :titulo, {:prompt=>"Selecciona un Idioma"}, {:class=>'form-control'} %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/agrupadores/edit.html.erb
<h1>Editar Agrupador</h1>

<%= render 'form' %>

<%= link_to 'Show', @agrupadore %> |
<%= link_to 'Back', agrupadores_path %>

app/views/agrupadores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Agrupadores</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agrupadores.each do |agrupadore| %>
      <tr>
        <td><%= agrupadore.titulo %></td>
        <td><%= agrupadore.idioma_id %></td>
        <td><%= link_to 'Show', agrupadore %></td>
        <td><%= link_to 'Edit', edit_agrupadore_path(agrupadore) %></td>
        <td><%= link_to 'Destroy', agrupadore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Agrupador', new_agrupadore_path %>

app/views/agrupadores/new.html.erb
<h1>Nuevo Agrupador</h1>

<%= render 'form' %>

<%= link_to 'Regresar', agrupadores_path %>

app/views/agrupadores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @agrupadore.titulo %>
   <strong>Idioma:</strong>
  <%= @agrupadore.idioma_id %>
  

</p>

<%= link_to 'Edit', edit_agrupadore_path(@agrupadore) %> |
<%= link_to 'Back', agrupadores_path %>