config/routes.rb
Rails.application.routes.draw do

  resources :likes
  resources :idiomas
  resources :noticia
  resources :agrupadores
  resources :estatuses
  resources :categoria

 namespace :api do
  namespace :v1 do 
    resources :noticia, path: "/news"
    resources :app
    resources :like , path: "/like"
  end
 end

    get 'noticia' => 'noticia#index', as: :noticia_index
    get 'categoria' => 'categoria#index', as: :categoria_index

end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
end

app/controllers/idiomas_controller.rb
class IdiomasController < ApplicationController
  before_action :set_idioma, only: [:show, :edit, :update, :destroy]

  # GET /idiomas
  # GET /idiomas.json
  def index
    @idiomas = Idioma.all
  end

  # GET /idiomas/1
  # GET /idiomas/1.json
  def show
  end

  # GET /idiomas/new
  def new
    @idioma = Idioma.new
  end

  # GET /idiomas/1/edit
  def edit
  end

  # POST /idiomas
  # POST /idiomas.json
  def create
    @idioma = Idioma.new(idioma_params)

    respond_to do |format|
      if @idioma.save
        format.html { redirect_to @idioma, notice: 'Idioma was successfully created.' }
        format.json { render :show, status: :created, location: @idioma }
      else
        format.html { render :new }
        format.json { render json: @idioma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idiomas/1
  # PATCH/PUT /idiomas/1.json
  def update
    respond_to do |format|
      if @idioma.update(idioma_params)
        format.html { redirect_to @idioma, notice: 'Idioma was successfully updated.' }
        format.json { render :show, status: :ok, location: @idioma }
      else
        format.html { render :edit }
        format.json { render json: @idioma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idiomas/1
  # DELETE /idiomas/1.json
  def destroy
    @idioma.destroy
    respond_to do |format|
      format.html { redirect_to idiomas_url, notice: 'Idioma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idioma
      @idioma = Idioma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idioma_params
      params.require(:idioma).permit(:titulo)
    end
end

app/helpers/idiomas_helper.rb
module IdiomasHelper
end

app/views/idiomas/_form.html.erb
<%= form_for(@idioma) do |f| %>
  <% if @idioma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idioma.errors.count, "error") %> prohibited this idioma from being saved:</h2>

      <ul>
      <% @idioma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/idiomas/edit.html.erb
<h1>Editing Idioma</h1>

<%= render 'form' %>

<%= link_to 'Show', @idioma %> |
<%= link_to 'Back', idiomas_path %>

app/views/idiomas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Idiomas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idiomas.each do |idioma| %>
      <tr>
        <td><%= idioma.titulo %></td>
        <td><%= link_to 'Show', idioma %></td>
        <td><%= link_to 'Edit', edit_idioma_path(idioma) %></td>
        <td><%= link_to 'Destroy', idioma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idioma', new_idioma_path %>

app/views/idiomas/new.html.erb
<h1>New Idioma</h1>

<%= render 'form' %>

<%= link_to 'Back', idiomas_path %>

app/views/idiomas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @idioma.titulo %>
</p>

<%= link_to 'Edit', edit_idioma_path(@idioma) %> |
<%= link_to 'Back', idiomas_path %>