config/routes.rb
Rails.application.routes.draw do

  resources :likes
  resources :idiomas
  resources :noticia
  resources :agrupadores
  resources :estatuses
  resources :categoria

 namespace :api do
  namespace :v1 do 
    resources :noticia, path: "/news"
    resources :app
    resources :like , path: "/like"
  end
 end

    get 'noticia' => 'noticia#index', as: :noticia_index
    get 'categoria' => 'categoria#index', as: :categoria_index

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :noticium
end

app/controllers/api/v1/like_controller.rb
class Api::V1::LikeController < ApplicationController
	def index
		if params[:type] == "likes"
			@conteo_like = Like.where(:noticium_id => params[:id]).where.not(:like => 0).count(:like)
			render json: 
			{
				likes: @conteo_like
			}
		end
		if params[:type] == "dislikes"
			@conteo_dislike = Like.where(:noticium_id => params[:id]).where.not(:dislike => 0).count(:dislike)
			render json: 
			{
				dislikes: @conteo_dislike
			}
		end
		if params[:type] == "like"
			@existe = Like.select("id").where(:noticium_id => params[:id]).where(:user_id => params[:user])
 			if @existe.blank?	
 				 @like = Like.create(
 						:like => 1,
 						:dislike => 0,
 						:noticium_id => params[:id],
 						:user_id => params[:user]
 						)

 				if @like.save
 					render json: {
 						status: "Ok"
 					}
 				end
 			else

 				@like_result = Like.select("like").where(:noticium_id => params[:id]).where(:user_id => params[:user])
 			   	     if @like_result[0].like === 0 
		 			   @like_result_id = Like.select("id").where(:noticium_id => params[:id]).where(:user_id => params[:user])
		 			   @busca_id = Like.find(@like_result_id[0].id)
		 			   @busca_id.update(:like => 1)
		 			   @busca_id.update(:dislike => 0)
		 				if @busca_id.save
		 					render json: {
		 						status: "Actualizacion Ok"
		 					}
						end
 					 else
 					 	render json: {
		 					status: "Usted ya cuenta con un like para esta noticia"
		 				}
	
				      end
 			end
 		end
 		if params[:type] == "dislike"
 			   @existe = Like.select("id").where(:noticium_id => params[:id]).where(:user_id => params[:user])
 			   if @existe.blank?
	 			   	@dislike = Like.create(
	 						:like => 0,
	 						:dislike => 1,
	 						:noticium_id => params[:id],
	 						:user_id => params[:user]
	 						)

	 				if @dislike.save
	 					render json: {
	 						status: "Dislike creado exitosamente"
	 					}
	 				end
 			   	else
 			   	     @dislike_result = Like.select("dislike").where(:noticium_id => params[:id]).where(:user_id => params[:user])
 			   	    if @dislike_result[0].dislike === 1 
		 			   render json: {
		 					status: "Usted ya cuenta con un dislike para esta noticia"
		 				}
 					else
 					   @dislike_result_id = Like.select("id").where(:noticium_id => params[:id]).where(:user_id => params[:user])
		 			   @busca_id = Like.find(@dislike_result_id[0].id)
		 			   @busca_id.update(:like => 0)
		 			   @busca_id.update(:dislike => 1)
		 				if @busca_id.save
		 					render json: {
		 						status: "Actualizacion Ok"
		 					}
						end
				    end
 			   end
		end
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:like, :dislike, :noticium_id, :user_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :like %><br>
    <%= f.number_field :like %>
  </div>
  <div class="field">
    <%= f.label :dislike %><br>
    <%= f.number_field :dislike %>
  </div>
  <div class="field">
    <%= f.label :noticium_id %><br>
    <%= f.text_field :noticium_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Likes</h1>

<table>
  <thead>
    <tr>
      <th>Like</th>
      <th>Dislike</th>
      <th>Noticium</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.like %></td>
        <td><%= like.dislike %></td>
        <td><%= like.noticium %></td>
        <td><%= like.user_id %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Like:</strong>
  <%= @like.like %>
</p>

<p>
  <strong>Dislike:</strong>
  <%= @like.dislike %>
</p>

<p>
  <strong>Noticium:</strong>
  <%= @like.noticium %>
</p>

<p>
  <strong>User:</strong>
  <%= @like.user_id %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>