config/routes.rb
Rails.application.routes.draw do

  resources :likes
  resources :idiomas
  resources :noticia
  resources :agrupadores
  resources :estatuses
  resources :categoria

 namespace :api do
  namespace :v1 do 
    resources :noticia, path: "/news"
    resources :app
    resources :like , path: "/like"
  end
 end

    get 'noticia' => 'noticia#index', as: :noticia_index
    get 'categoria' => 'categoria#index', as: :categoria_index

end

app/controllers/estatuses_controller.rb
class EstatusesController < ApplicationController
  before_action :set_estatus, only: [:show, :edit, :update, :destroy]

  # GET /estatuses
  # GET /estatuses.json
  def index
    @estatuses = Estatus.all
  end

  # GET /estatuses/1
  # GET /estatuses/1.json
  def show
  end

  # GET /estatuses/new
  def new
    @estatus = Estatus.new
  end

  # GET /estatuses/1/edit
  def edit
  end

  # POST /estatuses
  # POST /estatuses.json
  def create
    @estatus = Estatus.new(estatus_params)

    respond_to do |format|
      if @estatus.save
        format.html { redirect_to @estatus, notice: 'Estatus was successfully created.' }
        format.json { render :show, status: :created, location: @estatus }
      else
        format.html { render :new }
        format.json { render json: @estatus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estatuses/1
  # PATCH/PUT /estatuses/1.json
  def update
    respond_to do |format|
      if @estatus.update(estatus_params)
        format.html { redirect_to @estatus, notice: 'Estatus was successfully updated.' }
        format.json { render :show, status: :ok, location: @estatus }
      else
        format.html { render :edit }
        format.json { render json: @estatus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estatuses/1
  # DELETE /estatuses/1.json
  def destroy
    @estatus.destroy
    respond_to do |format|
      format.html { redirect_to estatuses_url, notice: 'Estatus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estatus
      @estatus = Estatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estatus_params
      params.require(:estatus).permit(:titulo)
    end
end

app/helpers/estatuses_helper.rb
module EstatusesHelper
end

app/views/estatuses/_form.html.erb
<%= form_for(@estatus) do |f| %>
  <% if @estatus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estatus.errors.count, "error") %> prohibited this estatus from being saved:</h2>

      <ul>
      <% @estatus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/estatuses/edit.html.erb
<h1>Editar Estatus</h1>

<%= render 'form' %>

<%= link_to 'Detalles', @estatus %> |
<%= link_to 'Regresar', estatuses_path %>

app/views/estatuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Estatus</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estatuses.each do |estatus| %>
      <tr>
        <td><%= estatus.titulo %></td>
        <td><%= link_to 'Detalles', estatus %></td>
        <td><%= link_to 'Editar', edit_estatus_path(estatus) %></td>
        <td><%= link_to 'Eliminar', estatus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Estatus', new_estatus_path %>

app/views/estatuses/new.html.erb
<h1>Nuevo Estatus</h1>

<%= render 'form' %>

<%= link_to 'Regresar', estatuses_path %>

app/views/estatuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @estatus.titulo %>
</p>

<%= link_to 'Editar', edit_estatus_path(@estatus) %> |
<%= link_to 'Regresar', estatuses_path %>